### ISSUE TITLE
incus admin init --minimal does not create a root disk device

### ISSUE THREAD

**Issue by itviewer** [lxc/incus#1200]
- Incus 6.5
- ubuntu 24.04.1

```
incus admin init --minimal
```
the output of  `incus profile show default`
```
config: {}
description: Default Incus profile
devices:
  eth0:
    name: eth0
    network: incusbr0
    type: nic
name: default
used_by: []
project: default
```
```
incus launch images:ubuntu/22.04 first
```
the error

```
Launching first
Error: Failed instance creation: Failed creating instance record: Failed initializing instance: Invalid devices: Failed detecting root disk device: No root device could be found
```

when init with interactive mode, `incus launch` can start the container normally

```
Would you like to use clustering? (yes/no) [default=no]: 
Do you want to configure a new storage pool? (yes/no) [default=yes]: 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (dir, btrfs) [default=btrfs]: dir
Where should this storage pool store its data? [default=/var/lib/incus/storage-pools/default]: 
Would you like to create a new local network bridge? (yes/no) [default=yes]: 
What should the new bridge be called? [default=incusbr0]: 
What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
Would you like the server to be available over the network? (yes/no) [default=no]: 
Would you like stale cached images to be updated automatically? (yes/no) [default=yes]: 
Would you like a YAML "init" preseed to be printed? (yes/no) [default=no]: 
```
the output of  `incus profile show default`
```
config: {}
description: Default Incus profile
devices:
  eth0:
    name: eth0
    network: incusbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by: []
project: default
```
