### ISSUE TITLE
OCI container config does not store a tag

### ISSUE THREAD

**Issue by ser** [lxc/incus#1273]
# Required information

* Incus version: 6.5

# Issue description

When I create an OCI container, I can see in the config:

```
image.description: docker.io/kimai/kimai2 (OCI)
```

in a case where the OCI was launched with

```
docker:kimai/kimai2:apache
```

The problem is that `docker.io/kimai/kimai2` and `docker.io/kimai/kimai2:apache` are two different images! So `incus --rebuild` destroys the correct image replacing it with a wrong one.

**Comment by stgraber** [comment]
```
stgraber@castiana:~/data/code/lxc/incus (stgraber/doc)$ incus image show oci-docker:kimai/kimai2:apache
auto_update: false
properties:
  architecture: x86_64
  description: docker.io/kimai/kimai2 (OCI)
  id: kimai/kimai2:apache
  type: oci
public: true
expires_at: 0001-01-01T00:00:00Z
profiles: []
```

This will now capture an `id` property which is based on what the user actually requested.
