### ISSUE TITLE
Instance config validation fails if managed and unmanaged bridged networks configured

### ISSUE THREAD

**Issue by tregubovav-dev** [lxc/incus#1494]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 24.04.1 Server
 * The output of "incus info" or if that fails:
   * Incus version: 6.7
   * Storage backend in use: Directory

# Issue description

Unable to configure 2 (or more) network interfaces in the instance config if both managed and unmanaged bridges are used.
Configuration validation fails with the message: `Config parsing error: Failed add validation for device "eth1": Instance DNS name "<instance name>" conflict between "eth1" and "eth0" because both are connected to same network
Press enter to open the editor again or ctrl+c to abort change`
# Steps to reproduce

 1. Ensure that the `Incus` deployment has managed and unmanaged bridges like below:
```
+----------+----------+---------+-----------------+--------------------------+-------------+---------+---------+
|   NAME   |   TYPE   | MANAGED |      IPV4       |           IPV6           | DESCRIPTION | USED BY |  STATE  |
+----------+----------+---------+-----------------+--------------------------+-------------+---------+---------+
| br-lan   | bridge   | NO      |                 |                          |             | 0       |         |
+----------+----------+---------+-----------------+--------------------------+-------------+---------+---------+
| br-wan   | bridge   | NO      |                 |                          |             | 0       |         |
+----------+----------+---------+-----------------+--------------------------+-------------+---------+---------+
| eth0     | physical | NO      |                 |                          |             | 0       |         |
+----------+----------+---------+-----------------+--------------------------+-------------+---------+---------+
| eth.2    | vlan     | NO      |                 |                          |             | 0       |         |
+----------+----------+---------+-----------------+--------------------------+-------------+---------+---------+
| eth.3    | vlan     | NO      |                 |                          |             | 0       |         |
+----------+----------+---------+-----------------+--------------------------+-------------+---------+---------+
| incusbr0 | bridge   | YES     | 10.148.214.1/24 | fd42:7773:cfe:e445::1/64 |             | 2       | CREATED |
+----------+----------+---------+-----------------+--------------------------+-------------+---------+---------+
| lo       | loopback | NO      |                 |                          |             | 0       |         |
+----------+----------+---------+-----------------+--------------------------+-------------+---------+---------+
```
 3. Initialize container using: `incus init images:alpine/edge <instance name>`
 4. Edit container config and add two network interfaces like below
```
devices:
  eth0:
    network: incusbr0
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: br-lan
    type: nic
```
5. Save config

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ incus init images:alpine/edge a1
Creating a1
stgraber@castiana:~$ incus config edit a1            
stgraber@castiana:~$ incus config show a1
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine edge amd64 (20241211_13:00)
  image.os: Alpine
  image.release: edge
  image.requirements.secureboot: "false"
  image.serial: "20241211_13:00"
  image.type: squashfs
  image.variant: default
  volatile.apply_template: create
  volatile.base_image: e269089a213d4f61cf72d31788ef10b47dc7ae901274c238cfd4239e0bf30ee6
  volatile.cloud-init.instance-id: d3236ca9-fd2f-4270-8fcb-5bfc4ba5d5b3
  volatile.eth0.hwaddr: 00:16:3e:59:28:b6
  volatile.eth0.name: eth0
  volatile.eth1.hwaddr: 00:16:3e:6a:19:09
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.uuid: f5a09705-96e3-44f4-8139-7597dcc72dc1
  volatile.uuid.generation: f5a09705-96e3-44f4-8139-7597dcc72dc1
devices:
  eth0:
    network: incusbr0
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: br-lan
    type: nic
ephemeral: false
profiles:
- default
stateful: false
description: ""
stgraber@castiana:~$ incus start a1
stgraber@castiana:~$ 
```

**Comment by stgraber** [comment]
Can you show `incus network show incusbr0`?

**Comment by stgraber** [comment]
And `incus profile show default`

**Comment by tregubovav-dev** [comment]
I have seen this issue on RPI4B (arm64 platform).

```
$ incus network show incusbr0
config:
  ipv4.address: 10.148.214.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:7773:cfe:e445::1/64
  ipv6.nat: "true"
description: ""
name: incusbr0
type: bridge
used_by:
- /1.0/profiles/default
managed: true
status: Created
locations:
- none
project: default
```

```
$ incus profile show default
config: {}
description: Default Incus profile
devices:
  eth0:
    name: eth0
    network: incusbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/instances/owrt
- /1.0/instances/alp
project: default
```

**Comment by stgraber** [comment]
Can you show `incus admin sql global "SELECT * FROM networks"`?

**Comment by stgraber** [comment]
Looking at the code, this particular error should only be possible if `eth1` is either pointing at a managed network (`network=` property) or if the `parent` value points to a managed network, otherwise the `d.network != nil` condition wouldn't match and so that potential error path would be skipped.

That seems to be what's happening for me locally when using the exact same configuration you're using.
So I wonder if there's some kind of phantom database record or something going on which is making the validation load `br-lan` as if it's a managed network.

**Comment by tregubovav-dev** [comment]
Hm.. I've tried one more time and configuration above is passed. 
I saw this issue several times today when I tried to configure 2 instances.
I need try all steps I did in the past.

**Comment by tregubovav-dev** [comment]
> incus admin sql global "SELECT * FROM networks"

$ incus admin sql global "SELECT * FROM networks"
+----+------------+----------+-------------+-------+------+
| ID | PROJECT ID |   NAME   | DESCRIPTION | STATE | TYPE |
+----+------------+----------+-------------+-------+------+
| 1  | 1          | incusbr0 |             | 1     | 0    |
+----+------------+----------+-------------+-------+------+

**Comment by stgraber** [comment]
Okay, so yeah, nothing unusual there.

As far as I can tell, the only two ways to get the error above in your case would be:

1) ```
  eth0:
    network: incusbr0
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: incusbr0
    type: nic
```

2) ```
  eth0:
    network: incusbr0
    type: nic
  eth1:
    name: eth1
    network: incusbr0
    type: nic
```

**Comment by tregubovav-dev** [comment]
This is my mistake. It fails in that configuration:
```
devices:
  eth1:
    network: incusbr0
    type: nic
  eth0:
    name: eth0
    nictype: bridged
    parent: br-lan
    type: nic
```

`default` profile adds 
```
devices:
  eth0:
    network: incusbr0
    type: nic
```
which makes this conflict.

P.S.
I use dedicated profiles for all instances in my cluster and forgot about `default` profile configuration in this case.
