### ISSUE TITLE
volume size/usage not reported

### ISSUE THREAD

**Issue by xorbug** [lxc/incus#1530]
# Required information

 * Distribution: Debian
 * Distribution version: 12 (bookworm)
 * The output of "incus info":
```
config:
auth_user_method: unix
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
driver: lxc | qemu
  driver_version: 6.0.2 | 9.0.4
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    uevent_injection: "true"
    unpriv_binfmt: "false"
    unpriv_fscaps: "true"
  kernel_version: 6.1.0-28-amd64
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Debian GNU/Linux
  os_version: "12"
  project: default
  server: incus
  server_clustered: false
  server_event_mode: full-mesh
  server_pid: 336507
  server_version: "6.8"
  storage: btrfs
  storage_version: "6.2"
  storage_supported_drivers:
  - name: lvm
    version: 2.03.16(2) (2022-05-18) / 1.02.185 (2022-05-18) / 4.47.0
    remote: false
  - name: lvmcluster
    version: 2.03.16(2) (2022-05-18) / 1.02.185 (2022-05-18) / 4.47.0
    remote: true
  - name: btrfs
    version: "6.2"
    remote: false
  - name: dir
    version: "1"
    remote: false
```

# Issue description

Incus reports no size for some volumes (only the ones in a "secondary" pool I have, whatever that means for incus). No usage is shown by `incus storage volume` `list` nor `info`. Compare for `list`:
```
# incus storage volume list poolA -c t,U -f compact
    TYPE       USAGE    
  container  1.73GiB    
  container  7.59MiB    
  container  23.71MiB   
  container  36.43MiB   
  container  69.07MiB   
  container  71.71MiB   
  container  142.42MiB  
  container  612.00KiB  
  container  980.00KiB  
  custom     2.76GiB    
  custom     13.48MiB   
  custom     15.86GiB   
  custom     16.00KiB   
  custom     16.00KiB   
  custom     25.06GiB   
  custom     34.69GiB   
  custom     147.53MiB

# incus storage volume list poolB -c t,U -f compact
    TYPE     USAGE  
  container         
  container         
  custom            
```
Both pools use btrfs backend.

Let me know if more infos are needed and thanks for your support.
