### ISSUE TITLE
incus starts dnsmasq on bridge even if dns.mode none and ipv[46].dhcp false

### ISSUE THREAD

**Issue by smemsh** [lxc/incus#1537]
In `internal/server/network/driver_bridge.go`, Incus gathers invocation flags to pass to a dnsmasq instance, and then makes a stub empty `dnsmasq.raw` config file so incus will not read system `dnsmasq.conf`.

Nowhere is a network's `dns.mode` setting consulted, except to avoid adding `-s`, `--interface-name` and `-S` options to dnsmasq invocation.  The daemon is still started even with `dns.mode=none` and the values of both `ipv4.dhcp=false` and `ipv6.dhcp=false`, it just doesn't get the above flags added to `dnsmasq` invocation in that case.

The daemon does not need to be started when nothing is using it (and explicitly disabled by configuration).  My use case is complete static host db in /etc/hosts, and static ip address, done by cloud-init.

I could use an unmanaged network, but I like the bridge being created and given an IP address by Incus, and also retain option to use managed nat/firewall later.  In the meantime, dnsmasq should not be started, as long as both dns and dhcp are not in use.

Incus v6.7

``` yaml
config:
  dns.mode: none
  ipv4.address: 10.32.192.1/22
  ipv4.dhcp: "false"
  ipv4.firewall: "false"
  ipv4.nat: "false"
  ipv6.address: none
  ipv6.dhcp: "false"
  ipv6.firewall: "false"
  ipv6.nat: "false"
description: ""
name: br0
type: bridge
used_by:
- /1.0/profiles/default
managed: true
status: Created
locations:
- none
project: default
```
