### ISSUE TITLE
Add ipv6.ndp configuration option to managed bridges

### ISSUE THREAD

**Issue by michacassola** [lxc/incus#1584]
Please add a configuration option to managed bridges to enable NDP proxying on the host side as is possible with routed nics.

The option would take the interface name(s?) where the NDP proxy entries should be added as shown down in the example (ip -6 neigh add proxy 2001:FFFF:AAAA::1234 dev ens3).

When a container is created the NDP proxy entries for the containers IPv6, which it got from the bridge, are added to the system by incus as is done with the routed nic.

The routed nic requires most of this being built into incus already. The checking of the sysctl config should be the same.

Example admin init dump:

```
networks:
- config:
    ipv4.address: 10.0.0.1/9
    ipv4.nat: "true"
    ipv6.address: 2000:FFFF:AAAA::1/64
    ipv6.dhcp: "false"
    ipv6.nat: "false"
    ipv6.routing: "true"
    ipv6.ndp: "ens3"
  description: ""
  name: incusbr0
  type: bridge
  project: default
```
