### ISSUE TITLE
`incus admin init --preseed` should allow adding a profile to a specific project

### ISSUE THREAD

**Issue by megheaiulian** [lxc/incus#1590]
The preseed init allows creating both projects and profiles but it does not allow creating a project in a specific project.

For example:

```yaml

profiles:
  - name: myprofile
    config: {}
    project: other_project 

project:
   name: other_project
   features:  {}

```
Should create the `myprofile` profile in the `other_project` project.
The same makes sense for networks & storage.

**Comment by megheaiulian** [comment]
@stgraber A question somewhat related to this:
Do you think it makes sense to bring changes I made to init in lxd to incus: https://github.com/canonical/lxd/pull/12426 ?

**Comment by stgraber** [comment]
Yeah, we can bring that in, it would probably be useful in some cases when defining profiles that use custom volumes or when figuring a server to use custom volumes for images or backups. 

Feel free to send your change as a PR here but note that you need to have full ownership of the changes you're sending, that is, you need to be the original author of all the commits you'd be taking from LXD as we are not under the same license and you therefore need the ability to relicense any code you take from LXD.

That's been the fun state of things since Canonical decided to relicense LXD under AGPLv3, they can still take our improvements at will, but we can't look at anything that lands in LXD without legal issues...

**Comment by megheaiulian** [comment]
@stgraber:
Does it make sense to also support projects when initializing storages ? 
This way you can prepare a preseed that can fully init a project with its own networks, storage, storage volume & profiles. 

This will be a tiny bit more complicated but similar to network I think we first need to create the storages for the  default project   and then init the other ones after projects are created, right ?

**Comment by jrowlandtexas** [comment]
hey what happened to this? I really need a "default" profile per-project for my setup and don't see this feature represented in 6.11 or it isn't made clear in docs.

**Comment by stgraber** [comment]
They are:
```
stgraber@dakara:~$ incus project create foo
Project foo created
stgraber@dakara:~$ incus project show foo
config:
  features.images: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
description: ""
name: foo
used_by:
- /1.0/profiles/default?project=foo
```
