### ISSUE TITLE
incus-migrate import failure when profile has a custom block volume attached.

### ISSUE THREAD

**Issue by Taverius** [lxc/incus#1657]
With a profile like so:
```yaml
config: {}
description: Test Profile
devices:
  openwrt_opt:
    pool: incus-zfs
    source: openwrt_opt
    type: disk
name: test
used_by: []
project: default
```

Where `openwrt_opt` is a 4GiB block device with an ext4 fs, if that matters.

`incus-migrate` state at import:
```yaml
Instance to be created:
  Name: OpenWRT-Test
  Project: default
  Type: virtual-machine
  Source: openwrt-24.10.0-x86-64-generic-ext4-combined-efi.img
  Source format: raw
  Profiles:
  - test
  Storage pool: incus-zfs
  Config:
    security.secureboot: "false"
```

Fails like so:

```
Please pick one of the options above [default=1]:
Transferring instance: OpenWRT-Test: 113.91MB (28.47MB/s)Error: Failed to prepare device "openwrt_opt" for migration: Not supported
```

Instance is not in `incus list`, but when exists in storage pool:

`❯ incus storage show incus-zfs`
```yaml
config:
  source: incus
  volatile.initial_source: /dev/disk/by-partlabel/disk-fast-incus
  zfs.pool_name: incus
description: ZFS on Micron 7450 800GB PCIe4.0x4
name: incus-zfs
driver: zfs
used_by:
- /1.0/images/7cc853ea6eff448c2ed87172fabde4f1b2614b3c4f68205a30b34a321dd4c2f5
- /1.0/instances/OpenWRT-Test
- /1.0/instances/alpine-vm
- /1.0/profiles/default
- /1.0/profiles/test
- /1.0/storage-pools/incus-zfs/volumes/custom/backups
- /1.0/storage-pools/incus-zfs/volumes/custom/images
- /1.0/storage-pools/incus-zfs/volumes/custom/openwrt_opt
status: Created
locations:
- none
```

`❯ incus storage volume list incus-zfs`
```
+-----------------+------------------------------------------------------------------+----------------------------+--------------+---------+
|      TYPE       |                               NAME                               |        DESCRIPTION         | CONTENT-TYPE | USED BY |
+-----------------+------------------------------------------------------------------+----------------------------+--------------+---------+
| custom          | backups                                                          | Backup Storage on ZFS      | filesystem   | 0       |
+-----------------+------------------------------------------------------------------+----------------------------+--------------+---------+
| custom          | images                                                           | Image Storage on ZFS       | filesystem   | 0       |
+-----------------+------------------------------------------------------------------+----------------------------+--------------+---------+
| custom          | openwrt_opt                                                      | OpenWRT Persistent Storage | block        | 1       |
+-----------------+------------------------------------------------------------------+----------------------------+--------------+---------+
| image           | 7cc853ea6eff448c2ed87172fabde4f1b2614b3c4f68205a30b34a321dd4c2f5 |                            | block        | 1       |
+-----------------+------------------------------------------------------------------+----------------------------+--------------+---------+
| virtual-machine | OpenWRT-Test                                                     |                            | block        | 1       |
+-----------------+------------------------------------------------------------------+----------------------------+--------------+---------+
| virtual-machine | alpine-vm                                                        |                            | block        | 1       |
+-----------------+------------------------------------------------------------------+----------------------------+--------------+---------+
```

Ref: https://discuss.linuxcontainers.org/t/migrate-failed-vm-in-pool-but-not-instance-list-how-to-remove-from-pool/
