### ISSUE TITLE
OVN bridge MTU not getting correctly advertised over DHCP

### ISSUE THREAD

**Issue by markrattray** [lxc/incus#1675]
Ubuntu Server 24.04.1 x86_64 6.8.0-52-generic
Incus 6.8
ovn-*  24.03.2-0ubuntu0.24.04.1

Most of my Windows Server 2022 VM instances on OVN networks are using MTU of 1500. These instances cannot get to some TLS sites and APIs. One e.g.: can’t even get to https://portal.azure.com 

Manually set the MTU to 1442 in these VM will get things working again. This doesn't happen on macvlan interface with the same MTU of 1500 in the same instance that's just switch networks.

The OVN network gets the following two configs set manually during creation because there are legacy networks around so we can't rely on auto allocation:
  -  `ipv4.addres`
  - `volatile.network.ipv4.address`

The `bridge.mtu` setting is auto added by Incus.

OVN network
```
config:
  bridge.mtu: "1442"
  dns.domain: subdomain1.domain.tld
  dns.search: subdomain1.domain.tld,subdomain2.domain.tld
  ipv4.address: 10.234.123.1/24
  ipv4.dhcp: "true"
  ipv4.nat: "false"
  ipv6.address: none
  ipv6.dhcp: "false"
  ipv6.nat: "false"
  network: somecluster-inu01
  volatile.network.ipv4.address: 10.0.1.2
description: ""
name: some-ovn-network01
type: ovn
used_by:
- /1.0/profiles/someprofile_ovn?project=some-project
managed: true
status: Created
locations:
- clustermember1
- clustermember2
- clustermember3
- clustermember4
- clustermember5
- clustermember6
```

The OVN UPLINK:
```
config:
  dns.nameservers: 10.0.0.24,10.0.0.25,10.0.0.26
  ipv4.gateway: 10.0.0.1/24
  ipv4.ovn.ranges: 10.0.0.100-10.0.0.254
  ipv4.routes: 10.0.1.0/24,10.0.2.0/24,10.0.4.0/24
  ovn.ingress_mode: routed
  volatile.last_state.created: "false"
description: 
name: somecluster-inu01
type: physical
used_by:
- /1.0/networks/some-ovn-network01?project=some-project
- ...
managed: true
status: Created
locations:
- clustermember1
- clustermember2
- clustermember3
- clustermember4
- clustermember5
- clustermember6
project: default
```

I originally thought this was an issue that needed solving at the DHCP service level but it looks like it more complicated after reading this:
https://superuser.com/a/655258
