### ISSUE TITLE
Possible issue with io.bus=nvme on Windows?

### ISSUE THREAD

**Issue by foxtrotcz** [lxc/incus#1693]
1) I was testing usability of Windows **without Virtio drivers**. (Incus 6.0.3 from Debian and Incus 6.9 from Zabbly)
I thought Windows 11 is supposed to be able to be installed on NVMe disk without any additional drivers.
But looks like its not working. I set root disk with `io.bus: nvme` but Windows 11 (and Windows Server 2025) installer doesnt see the disk.
```
root:
    io.bus: nvme
    path: /
    pool: default
    size: 55GiB
    type: disk
```

2) On Windows 10 I also tried mounting ISO file via NVMe bus but this also didnt work and I couldnt see the ISO. (Incus 6.0.3 from Debian)
```
mydisk:
    io.bus: nvme
    source: /home/user/mydisk.iso
    type: disk
```

Is this bug or is this working as expected? Can someone test this? Maybe I am doing something wrong.
Thanks.
