### ISSUE TITLE
IOMMU emulation sometimes triggers kernel boot issue

### ISSUE THREAD

**Issue by tregubovav-dev** [lxc/incus#1712]
Newly deployed or rebuild VM does not boot as `root` device unavailable. Issue is reproduced with `ubuntu/24.04` and `alpine/edge` images on `ARM` and `X86_64` architectures.

#### Steps to reproduce:
* Launch VM with the command `incus launch <image> <VM> --console`. 
#### Expected result:
VM should boot and login prompt should appear in the console.
#### Actual result:
VM boot falls to `initramfs emergency recovery shell` as `root` device coiuld not be found.
#### VM console snippet:
```
[    3.319393] Mounting root...
 * Mounting root: [    8.525998] UUID=8d6b7fa4-4c8a-4326-ab14-af046e81591f: Can't lookup blockdev
mount: mounting UUID=8d6b7fa4-4c8a-4326-ab14-af046e81591f on /sysroot failed: No such file or directory
[    8.533904] Mounting root: failed.
failed.
initramfs emergency recovery shell launched. Type 'exit' to continue boot
```
#### Instance config:
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine edge amd64 (20250301_13:00)
  image.os: Alpine
  image.release: edge
  image.requirements.secureboot: "false"
  image.serial: "20250301_13:00"
  image.type: disk-kvm.img
  image.variant: default
  security.secureboot: "false"
  volatile.base_image: 3550865f5d496341f86f2e3f61394867d61e321772656bd69f9f366b83de404d
  volatile.cloud-init.instance-id: 0a3c2bd8-af2f-4169-8f13-d39010bc7046
  volatile.eth0.host_name: tapb7a02be3
  volatile.eth0.hwaddr: 00:16:3e:68:16:b9
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: 46f1417b-76ae-472b-b7d2-c44d5c6dad44
  volatile.uuid.generation: 46f1417b-76ae-472b-b7d2-c44d5c6dad44
  volatile.vsock_id: "3276276466"
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
#### Full VM startup log:
[VM.log](https://github.com/user-attachments/files/19041908/VM.log)
