### ISSUE TITLE
Create network ignore --project flag

### ISSUE THREAD

**Issue by tlvenn** [lxc/incus#1724]
Hi,

I am trying to create a network that is belonging to a custom project so when i create it, i do:
`incus network create my_network --project my_project`

The command works but  `incus network show my_network` reveals that the network belongs to the default project:
```
config:
  ipv4.address: 10.214.191.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:b89f:d8cb:52c7::1/64
  ipv6.nat: "true"
description: ""
name: my_network
type: bridge
used_by: []
managed: true
status: Created
locations:
- none
project: default
```

Incus version:
```
Client version: 6.10.1
Server version: 6.10.1
```

**Comment by stgraber** [comment]
Can you show `incus project show my_project`?

**Comment by tlvenn** [comment]
```
config:
  features.images: "true"
  features.networks: "false"
  features.networks.zones: "false"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
description: ""
name: my_project
used_by:
- /1.0/profiles/default?project=my_project
```
