### ISSUE TITLE
IPv6 cannot be set on container

### ISSUE THREAD

**Issue by cezardimoiu** [lxc/incus#1755]
This is my default network for incus, but if I change the ipv6 address to `fd56:bb4d:be2d::1/112`, the container cannot assign an ipv6, but only ipv4. Looks like only `/64` is working
```
config:
  ipv4.address: 192.168.124.1/24
  ipv4.nat: "true"
  ipv6.address: fd56:bb4d:be2d::1/64
  ipv6.nat: "true"
description: ""
name: incusbr0
type: bridge
used_by:
- /1.0/profiles/default
- /1.0/instances/test-container
managed: true
status: Created
locations:
- none
project: default
```
