### ISSUE TITLE
Option to configure the default console for instances

### ISSUE THREAD

**Issue by ecapson** [lxc/incus#2054]
### Is there an existing issue for this?

- [x] There is no existing issue for this feature

### What are you currently unable to do

Currently the console is not configurable by instance basis and not possible to add arguments without a workaround on the OS. for ex: incus console instance --type=vga will launch spicy or remote-viewer. 

### What do you think would need to be added

It would be nice to be able to define default console behaviour in the instance config.
ex yaml config with incus config edit instance: 
console.type = console or vga
console.executable = /usr/bin/somespice-bin
console.args = [somespice-bin args]

**Comment by stgraber** [comment]
This wouldn't be an instance config as those are server-side and it makes no sense for the server side config to keep track of client side preferences.

But we're adding support for more "default" options in the CLI so that could fit in there.

**Comment by efficacy38** [comment]
hello @stgraber, I think I can take this issue.

My current thought is to add a config under `XDG_CONFIG_HOME/incus/console.yml`, which has the following structure. 

```
  virtual-machine: vga
  container: console
  override:
      - project: deafult
        instance: c1
        type: vga
      - project: deafult
        instance: v1
        type: console
```

Does it make sense?
