### ISSUE TITLE
Issue running/installing ssh daemon inside ubuntu incus containers

### ISSUE THREAD

**Issue by technicalflow** [lxc/incus#2070]
### Is there an existing issue for this?

- [x] There is no existing issue for this bug

### Is this happening on an up to date version of Incus?

- [x] This is happening on a supported version of Incus

### Incus system details

```yaml
driver: lxc | qemu
  driver_version: 6.0.4 | 9.0.4
  os_name: Ubuntu
  os_version: "24.04"
  project: default
  server: incus
  server_clustered: false
  server_event_mode: full-mesh
  server_name: sv-sigma
  server_pid: 1219
  server_version: 6.0.4
  storage: dir
  kernel_version: 6.8.0-53-generic
```

### Current behavior

Hello,

I got strange issue running or installing openssh-server package in all ubuntu based containers (on debian works normaly)
I receive:
systemctl enable sshd
Failed to enable unit: Unit file sshd.service does not exist.

### Steps to reproduce

Run any debian/ubuntu image
install ssh daemon
