### ISSUE TITLE
Too many levels of symbolic links - Failed to open rootfs "/opt/incus/lib/lxc/rootfs"

### ISSUE THREAD

**Issue by strk** [lxc/incus#2098]
### Is there an existing issue for this?

- [x] There is no existing issue for this bug

### Is this happening on an up to date version of Incus?

- [x] This is happening on a supported version of Incus

### Incus system details

```yaml
icus info output is huge

It's incus package 1:6.0.4-ubuntu22.04-202504072335 
installed from https://pkgs.zabbly.com/incus/lts-6.0 on Ubuntu jammy
```

### Instance details

```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Debian trixie amd64 (20250507_06:23)
  image.os: Debian
  image.release: trixie
  image.serial: "20250507_06:23"
  image.type: squashfs
  image.variant: default
  volatile.base_image: acc0fbba52b4e347d17e06ebf6b0b9b8527ad47ad260b07d6a5a18f327077990
  volatile.cloud-init.instance-id: 7d2aa7c3-e192-4803-abe0-f5da002e74b3
  volatile.eth0.hwaddr: 10:66:6a:b5:ba:bd
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
  volatile.last_state.ready: "false"
  volatile.uuid: 288dd704-6fb4-459d-9f7e-1a73f1086740
  volatile.uuid.generation: 288dd704-6fb4-459d-9f7e-1a73f1086740
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

### Instance log

```
Name: trixie
Description: 
Status: STOPPED
Type: container
Architecture: x86_64
Created: 2025/05/08 11:46 CEST
Last Used: 2025/05/08 12:09 CEST

Log:

lxc trixie 20250508100902.125 ERROR    conf - ../src/lxc/conf.c:lxc_mount_rootfs:1250 - Too many levels of symbolic links - Failed to open rootfs "/opt/incus/lib/lxc/rootfs"
lxc trixie 20250508100902.125 ERROR    conf - ../src/lxc/conf.c:lxc_setup_rootfs_prepare_root:3504 - Failed to setup rootfs for
lxc trixie 20250508100902.125 ERROR    conf - ../src/lxc/conf.c:lxc_setup:3879 - Failed to setup rootfs
lxc trixie 20250508100902.125 ERROR    start - ../src/lxc/start.c:do_start:1273 - Failed to setup container "trixie"
lxc trixie 20250508100902.126 ERROR    sync - ../src/lxc/sync.c:sync_wait:34 - An error occurred in another process (expected sequence number 3)
lxc trixie 20250508100902.135 WARN     network - ../src/lxc/network.c:lxc_delete_network_priv:3674 - Failed to rename interface with index 0 from "eth0" to its initial name "veth97718890"
lxc trixie 20250508100902.135 ERROR    lxccontainer - ../src/lxc/lxccontainer.c:wait_on_daemonized_start:837 - Received container state "ABORTING" instead of "RUNNING"
lxc trixie 20250508100902.135 ERROR    start - ../src/lxc/start.c:__lxc_start:2119 - Failed to spawn container "trixie"
lxc trixie 20250508100902.135 WARN     start - ../src/lxc/start.c:lxc_abort:1037 - No such process - Failed to send SIGKILL via pidfd 17 for process 1258511
lxc 20250508100902.192 ERROR    af_unix - ../src/lxc/af_unix.c:lxc_abstract_unix_recv_fds_iov:218 - Connection reset by peer - Failed to receive response
lxc 20250508100902.192 ERROR    commands - ../src/lxc/commands.c:lxc_cmd_rsp_recv_fds:128 - Failed to receive file descriptors for command "get_init_pid"
```

### Current behavior

incus start trixie # Error: Failed to run: /home/opt/incus/bin/incusd forkstart trixie /var/lib/incus/containers /run/incus/trixie/lxc.conf: exit status 1

### Expected behavior

incus start trixie # works, we're all happy

### Steps to reproduce

1. ln -sf /home/opt /opt
2. install incus
3. incus admin init --minimal
4. incus launch images:debian/trixie trixie
