### ISSUE TITLE
systemd credentials for containers

### ISSUE THREAD

**Issue by gwenya** [lxc/incus#2182]
### Is there an existing issue for this?

- [x] There is no existing issue for this feature

### What are you currently unable to do

[Systemd credentials](https://systemd.io/CREDENTIALS/) are key/value pairs that can be securely passed to systemd services. They are suitable both for actual secrets and for general configuration. 
In VMs, credentials can be passed from the host to the guest systemd via SMBIOS type 11 strings, which incus already supports nicely.
For containers, passing credentials from the host to the guest systemd works by mounting them into the container and passing the mount path in the environment variable `$CREDENTIALS_DIRECTORY`. This is somewhat supported by incus since arbitrary environment variables and mounts are possible, but it requires the user to manually prepare the credentials in a host directory or volume which is rather inconvenient.

### What do you think would need to be added

Add a new disk device source:

```yaml
devices: 
  credentials:
    type: disk
    source: credentials
    credentials-binary.foo: Zm9vCg==
    credentials.password: hunter2
    path: /run/incus-credentials
```

The user could then configure the `CREDENTIALS_DIRECTORY` environment variable to be `"/run/incus-credentials"` so that systemd can pick them up.

These credentials would only be as secure as the instance config is, i.e. anyone with read access via incus or directly to the incus database can extract them. At a later point they could be extended with (more secret) credentials from some external store (e.g. systemd on the host itself, or something like Hashicorp Vault / OpenBao).
