### ISSUE TITLE
custom freebsd vm does not boot after adding 7th network interface

### ISSUE THREAD

**Issue by hi-ko** [lxc/incus#397]
* Server Distribution: Ubuntu 
 * Distribution version: 22.04
 * incus Client version: 0.4
 * incus Server version: 0.4

# custom freebsd vm does not boot after adding 7th network interface

When creating a new custom vm by insgtalling freebsd from iso the vm does not boot after adding a 7th network device

# Steps to reproduce

1. create new vm and install freeBSD
```
VM=freebsd
# create emty vm to install new OS
incus init $VM --empty --vm -c limits.cpu=1 -c limits.memory=2GB -c security.secureboot=false -n br0 # -n br0
incus config device override $VM root size=15GB # resize the pfsense disk
echo -n '-machine pc-q35-2.6' | sudo incus config set $VM raw.qemu - # change the machine type with qemu parameter.

wget http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/amd64/ISO-IMAGES/14.0/FreeBSD-14.0-RELEASE-amd64-bootonly.iso
incus config device add $VM install disk source=$PWD/FreeBSD-14.0-RELEASE-amd64-bootonly.iso boot.priority=10 # Add boot disk image to the incus vm
```
2. remove install iso
```
incus config device remove $VM install
```
3. add 5 more network interfaces
```
incus config device add $VM eth1 nic nictype=bridged parent=br2
incus config device add $VM eth2 nic nictype=bridged parent=br2
incus config device add $VM eth3 nic nictype=bridged parent=br2
incus config device add $VM eth4 nic nictype=bridged parent=br2
incus config device add $VM eth5 nic nictype=bridged parent=br2
```
5. test boot and shutdown
```
incus start $VM && incus console $VM --type=vga
```
6. shutdown again and add another network interface
```
incus config device add $VM eth6 nic nictype=bridged parent=br2
```
OS hangs in boot

config is just vanilla:

```
incus config show $VM --expanded
architecture: x86_64
config:
  limits.cpu: "1"
  limits.memory: 2GB
  raw.qemu: -machine pc-q35-2.6
  security.secureboot: "false"
  volatile.cloud-init.instance-id: 929c778b-c249-4704-9491-2880669d42ec
  volatile.eth0.hwaddr: 00:16:3e:96:42:80
  volatile.eth1.hwaddr: 00:16:3e:e2:6a:39
  volatile.eth2.hwaddr: 00:16:3e:44:79:76
  volatile.eth3.hwaddr: 00:16:3e:c8:c7:81
  volatile.eth4.hwaddr: 00:16:3e:ed:76:68
  volatile.eth5.hwaddr: 00:16:3e:a2:5f:42
  volatile.last_state.power: STOPPED
  volatile.last_state.ready: "false"
  volatile.uuid: 54f49dab-3866-4524-a922-671739861368
  volatile.uuid.generation: 54f49dab-3866-4524-a922-671739861368
  volatile.vsock_id: "1725261566"
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  eth1:
    nictype: bridged
    parent: br2
    type: nic
  eth2:
    nictype: bridged
    parent: br2
    type: nic
  eth3:
    nictype: bridged
    parent: br2
    type: nic
  eth4:
    nictype: bridged
    parent: br2
    type: nic
  eth5:
    nictype: bridged
    parent: br2
    type: nic
  root:
    path: /
    pool: hdd1
    size: 15GB
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
## Additional Info

The issue does not happen when creating a vm from ubuntu cloud image (e.g. images:ubuntu/22.04/cloud). When adding more then 6 interfaces to a ubuntu cloud image based vm 
```
incus config device add test1 eth5 nic nictype=bridged parent=br2
Error: Failed to start device "eth5": Failed setting up device "eth5": Failed adding NIC device: Bus 'qemu_pcie9' not found
```
but after a reboot it is possible to add more network interfaces
