### ISSUE TITLE
Feature request: flag to append to property when using `incus launch --profile`

### ISSUE THREAD

**Issue by joshenders** [lxc/incus#472]
# Required information

 * Distribution: Debian
 * Distribution version: 12
 * The output of "incus info" or if that fails:
   * Kernel version: 6.1.0-17-amd64
   * LXC version: 5.0.3
   * Incus version: 0.5
   * Storage backend in use: disk

# Issue description

This may be a pebkac or a wontfix and that's a totally acceptable outcome––I just wanted to share my experience in case it might help inform the real world usage/ergonomics of the incus cli.

When using the `-c, --config` option to `incus launch`, my expectation is that the value for the key would be appended to the matching key specified in the instance profile. What happens instead is that value is overridden entirely. It becomes more cumbersome to use a generalized instance profile and then specialize the config at launch time, as I'm finding myself duplicating a lot of information that applies to each instance. Another option would of course to create separate profiles but again, more needless duplication.

# Steps to reproduce

> `lxc profile show flatcar`

```yaml
config:
  boot.autostart: "true"
  boot.stop.priority: "1"
  limits.cpu: 0,1
  limits.memory: 48GiB
  limits.memory.swap: "false"
  raw.apparmor: |-
    /opt/incus/share/qemu/flatcar_production_qemu_uefi_efi_code.fd rk,
    /opt/incus/share/qemu/flatcar_production_qemu_uefi_efi_vars.fd rwk,
  raw.qemu: |-
    -drive if=pflash,format=raw,file="/opt/incus/share/qemu/flatcar_production_qemu_uefi_efi_code.fd",readonly=on
    -drive if=pflash,format=raw,file="/opt/incus/share/qemu/flatcar_production_qemu_uefi_efi_vars.fd"
  raw.qemu.conf: |-
    [drive][0]
    [drive][1]
  security.secureboot: "false"
description: Container Host
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    size: 16GiB
    type: disk
name: flatcar
used_by: []
```

I'd prefer to launch instances using this profile like this:

```sh
incus launch --profile flatcar --vm local:"flatcar/${VERSION}" flatcar -c raw.qemu="-fw_cfg name=opt/org.flatcar-linux/config,file='${IGNITION_CONFIG}'"
```

but instead I must launch them like this:

```sh
incus launch --profile flatcar --vm local:"flatcar/${VERSION}" flatcar -c raw.qemu="-fw_cfg name=opt/org.flatcar-linux/config,file='${IGNITION_CONFIG}' -drive if=pflash,format=raw,file="/opt/incus/share/qemu/flatcar_production_qemu_uefi_efi_code.fd",readonly=on -drive if=pflash,format=raw,file="/opt/incus/share/qemu/flatcar_production_qemu_uefi_efi_vars.fd""
```
