### ISSUE TITLE
vm with custom storage block volume fails to start with: Cannot add un-shared custom storage block volume

### ISSUE THREAD

**Issue by hi-ko** [lxc/incus#530]
* Distribution: Ubuntu 
 * Distribution version: 22.04
 * Incus version: 0.6
 * Storage backend in use: zfs

existing vm having a second disk attached fails to start after update to incus version 0.6 with:
```
Error: Failed start validation for device "c1-swap": Cannot add un-shared custom storage block volume to more than one instance
```

# Steps to reproduce

 1. create  and stop vm
 2. create custom storage volume
 3. attach custom storage volume to the created vm
 4. start vm --> fails with above error message

```
incus storage volume show ssd1 c1-swap
config:
  security.shared: "true"
  size: 8GB
description: ""
name: c1-swap
type: custom
used_by:
- /1.0/instances/c1
location: none
content_type: block
project: default
```
