### ISSUE TITLE
Multicast vxlan tunnel ignores local address setting

### ISSUE THREAD

**Issue by XeCycle** [lxc/incus#537]
# Required information

 * Distribution: Arch Linux
 * Distribution version: N/A
 * The output of "incus info" or if that fails:
   * Kernel version: 6.7.6-arch1-1
   * LXC version: lxc 1:5.0.3-1
   * Incus version: incus 0.6.0-1
   * Storage backend in use: zfs

# Issue description

Kernel allows a multicast vxlan to have a local address configured, but incus does not set it.  This can affect peers' learned FDB entries.

# Steps to reproduce

 1. create a bridge network
 2. add a vxlan tunnel, be sure to include settings: group, interface, local

For example I have
```yaml
config:
  ipv4.address: none
  ipv6.address: none
  tunnel.vx.group: ff04::1
  tunnel.vx.id: "42"
  tunnel.vx.interface: vbr0
  tunnel.vx.local: fd7c:f71b:64dd::1
  tunnel.vx.port: "4789"
  tunnel.vx.protocol: vxlan
description: ""
name: icdemo
type: bridge
used_by: []
managed: true
status: Created
locations:
- none
```

And what I get on the tunnel interface is:
```
14: icdemo-vx: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master icdemo state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 8e:54:15:85:84:54 brd ff:ff:ff:ff:ff:ff promiscuity 1 allmulti 1 minmtu 68 maxmtu 65535 
    vxlan id 42 group ff04::1 dev vbr0 srcport 0 0 dstport 4789 ttl 1 ageing 300
```

It doesn't contain "local fd7c:f71b:64dd::1" after "group ff04::1".

Relevant code: https://github.com/lxc/incus/blob/284cb4da4335c0db9636dfeccf497bcaeb9b6fe1/internal/server/network/driver_bridge.go#L1185-L1203

I think we should also check and assign `Local` from `tunLocal` on the multicast code path.
