### ISSUE TITLE
Failed creating instance from image: No mountinfo entry found

### ISSUE THREAD

**Issue by cfredericksen** [lxc/incus#579]
I cannot create any vm instances. No matter the vm ISO picked. I always get this error. I can create containers but not vms. I am new to Incus and I am very impressed but I dont understand this error. I have restarted my Incus server.
Incus 0.6
Ubuntu 20.04 as host OS

My storage is 
local | btrfs with plenty of storage available

[local](https://192.168.1.13:8443/ui/project/kubernetes/storage/detail/local)	btrfs
```
Instance creation failed
Failed creating instance from image: No mountinfo entry found
```
Config
```
name: test
type: virtual-machine
devices:
  root:
    path: /
    pool: local
    type: disk
source:
  alias: alpine/3.16/default
  mode: pull
  protocol: simplestreams
  server: https://images.linuxcontainers.org
  type: image
config: {}
```
