### ISSUE TITLE
Cluster group restriction not respected on instance move between projects

### ISSUE THREAD

**Issue by victoitor** [lxc/incus#589]
# Issue description

Moving an instance between projects in a cluster maintains the instance on the same machine. This remains true even if the different projects have different values for `restricted.cluster.groups`, which creates an inconsistent state.

# Steps to reproduce

 1. Have projects with different cluster groups, as follows.
 I currently have projects set up to be restricted to cluster groups as follows.
```
victoitor@bastion:~$ incus project show dedicado
config:
  features.images: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
  limits.instances: "3"
  restricted: "true"
  restricted.backups: allow
  restricted.cluster.groups: dedicado
  restricted.cluster.target: allow
  restricted.containers.lowlevel: allow
  restricted.containers.nesting: allow
  restricted.devices.nic: allow
  restricted.snapshots: allow
description: Experimentos - máquinas dedicadas
name: dedicado
(...)
victoitor@bastion:~$ incus project show aux
config:
  features.images: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
  restricted: "true"
  restricted.backups: allow
  restricted.cluster.groups: compartilhado
  restricted.cluster.target: allow
  restricted.containers.lowlevel: allow
  restricted.containers.nesting: allow
  restricted.devices.nic: allow
  restricted.snapshots: allow
description: Containers com baixo recurso
name: aux
(...)
```
 2. Create an instance in one of the projects
 ```
pargo@bastion:~$ incus init images:debian/12 test --project dedicado
Creating test
pargo@bastion:~$ incus list test --project dedicado
+------+---------+------+------+-----------+-----------+------------+
| NAME |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |  LOCATION  |
+------+---------+------+------+-----------+-----------+------------+
| test | STOPPED |      |      | CONTAINER | 0         | dedicado02 |
+------+---------+------+------+-----------+-----------+------------+
```
 3. Move it to the second project
```
pargo@bastion:~$ incus list test --project aux
+------+---------+------+------+-----------+-----------+------------+
| NAME |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |  LOCATION  |
+------+---------+------+------+-----------+-----------+------------+
| test | STOPPED |      |      | CONTAINER | 0         | dedicado02 |
+------+---------+------+------+-----------+-----------+------------+
```
4. Since the move does not change the cluster member, the instance is not in a cluster member allowed by `restricted.cluster.groups`.

# Relevant information

It should be noted that copy correctly moves the instance.
```
pargo@bastion:~$ incus init images:debian/12 test --project dedicado
Creating test
pargo@bastion:~$ incus list test --project dedicado
+------+---------+------+------+-----------+-----------+------------+
| NAME |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |  LOCATION  |
+------+---------+------+------+-----------+-----------+------------+
| test | STOPPED |      |      | CONTAINER | 0         | dedicado02 |
+------+---------+------+------+-----------+-----------+------------+
pargo@bastion:~$ incus copy test test --project dedicado --target-project aux
pargo@bastion:~$ incus list test --project aux
+------+---------+------+------+-----------+-----------+-----------------+
| NAME |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |    LOCATION     |
+------+---------+------+------+-----------+-----------+-----------------+
| test | STOPPED |      |      | CONTAINER | 0         | compartilhado04 |
+------+---------+------+------+-----------+-----------+-----------------+
```

This was initially discussed in [this forum post](https://discuss.linuxcontainers.org/t/moving-instances-between-projects-with-cluster-groups/).
