### ISSUE TITLE
No mountinfo entry found when launching VM

### ISSUE THREAD

**Issue by technicalflow** [lxc/incus#832]
* Distribution: Ubuntu 
 * Distribution version: Focal 20.04
 * The output of "incus info" or if that fails:
   * Kernel version:  5.4.0-177-generic
   * LXC version: 6.0.0
   * Incus version: 6.0.0
   * Storage backend in use: btrfs

# Issue description
Hello Everyone,
Installed incus 6.0.0 on Ubuntu 20.04.
Containers works as expected but I receive this error when launching a VM:
Error: Failed instance creation: Failed creating instance from image: No mountinfo entry found

I tried creating new storage pool but got the same error.
On the same host libvirt and vagrant are running without issues

# Steps to reproduce

 1. Step one
 Launch vm:  incus launch images:ubuntu/focal/cloud u2 --vm
Error: 
Launching u2
Error: Failed instance creation: Failed creating instance from image: No mountinfo entry found

# Information to attach
my default profile:
config: {}
description: Default Incus profile
devices:
  eth0:
    name: eth0
    network: incusbr0
    type: nic
  root:
    path: /
    pool: isp1
    type: disk
name: default
used_by:

Image info
Fingerprint: 0120d96cedfa15e06248882a6cdb4392ce94177e738716a99aa9e78a439fa613
Size: 266.78MiB
Architecture: x86_64
Type: virtual-machine
Public: no
Timestamps:
    Created: 2024/05/03 02:00 CEST
    Uploaded: 2024/05/04 09:44 CEST
    Expires: 1970/01/01 01:00 CET
    Last used: 2024/05/04 09:44 CEST
Properties:
    variant: cloud
    architecture: amd64
    description: Ubuntu focal amd64 (20240503_07:42)
    os: Ubuntu
    release: focal
    serial: 20240503_07:42
    type: disk-kvm.img
Aliases:
Cached: yes
Auto update: enabled
Source:
    Server: https://images.linuxcontainers.org
    Protocol: simplestreams
    Alias: ubuntu/focal/cloud
Profiles:
    - default

**Comment by stgraber** [comment]
Can you show:
 - `incus storage list`
 - `incus storage show default`
 - `cat /proc/self/mountinfo`

**Comment by technicalflow** [comment]
Yes, sure:
incus storage list -f csv
```
incusstoragepool,btrfs,/var/lib/incus/disks/incusstoragepool.img,,3,CREATED
isp1,btrfs,/var/lib/incus/disks/isp1.img,,2,CREATED
```

incus storage show incusstoragepool
```
config:
  size: 100GiB
  source: /var/lib/incus/disks/incusstoragepool.img
description: ""
name: incusstoragepool
driver: btrfs
used_by:
- /1.0/images/677d030191fc6840d4f0c058c2473631398239471807398ee441dfb1ce6db54b?project=user-1000
- /1.0/profiles/macvlan
- /1.0/profiles/vmmacvlan
status: Created
locations:
- none

```
cat /proc/self/mountinfo #Incus related
```
654 30 0:52 / /var/lib/incus-lxcfs rw,nosuid,nodev,relatime shared:257 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
410 30 0:54 / /var/lib/incus/shmounts rw,relatime shared:326 - tmpfs tmpfs rw,size=100k,mode=711
423 30 0:55 / /var/lib/incus/guestapi rw,relatime shared:333 - tmpfs tmpfs rw,size=100k,mode=755
437 30 0:56 / /var/lib/incus/storage-pools/incusstoragepool rw,relatime shared:340 - btrfs /dev/loop0 rw,ssd,space_cache,user_subvol_rm_allowed,subvolid=5,subvol=/
450 30 0:58 / /var/lib/incus/storage-pools/isp1 rw,relatime shared:347 - btrfs /dev/loop1 rw,ssd,space_cache,user_subvol_rm_allowed,subvolid=5,subvol=/
```
