### ISSUE TITLE
Unable to create pulseaudio socket in container

### ISSUE THREAD

**Issue by cquike** [lxc/incus#856]
# Required information

 * Distribution: Fedora 40 and Debian 12
[incus_info.txt](https://github.com/lxc/incus/files/15245956/incus_info.txt)

# Issue description

I have created a profile to get pulseaudio access in the container using device of type proxy. This has been working fine in the past with lxc but I am not able to make it work with incus. The device is not created in the container.
# Steps to reproduce

 1. incus profile create pulseaudio
 2. incus profile edit pulseaudio
```
config:
  environment.PULSE_SERVER: unix:/run/pulse_native
description: Pulseaudio Incus profile
devices:
  PASocket1:
    bind: container
    connect: unix:/run/user/1111/pulse/native
    listen: unix:/run/pulse_native
    mode: "0777"
    type: proxy
name: pulseaudio
```
 4. incus launch -p pulseaudio -p default images:ubuntu/22.04 ubu2204-pa
 5. incus exec  ubu2204-pw -- ls -l /run

This should show the /run/pulse_native socket, but nothing is created. I have tried both in a Fedora 40 host (using the ganto/lxc4) and Debian 12 (using incus/bookworm-backports).  In neither of the cases works and I don't see any error message in the host logs shown by journalctl.
The container logs are also empty.

# Information to attach

 - [ X] Container configuration (`incus config show NAME --expanded`)

```
config:
  image.architecture: amd64
  image.description: Ubuntu jammy amd64 (20240507_07:42)
  image.os: Ubuntu
  image.release: jammy
  image.serial: "20240507_07:42"
  image.type: squashfs
  image.variant: default
  volatile.base_image: c43b4db4a5d19d4e9b8812e2895fd67c18735c58729e45eeb16caed37f9481d3
  volatile.cloud-init.instance-id: f1a417f3-85e0-4a38-867a-c249da8a27ac
  volatile.eth0.host_name: vethf665b759
  volatile.eth0.hwaddr: 00:16:3e:8d:10:0d
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: eff2dffd-527f-46e9-bdac-ea677041e401
  volatile.uuid.generation: eff2dffd-527f-46e9-bdac-ea677041e401
devices:
  PwSocket1:
    bind: container
    connect: unix:/run/user/4876/pulse/native
    listen: unix:/run/pipe-native
    mode: "0777"
    type: proxy
  eth0:
    name: eth0
    network: incusbr0
    type: nic
  root:
    path: /
    pool: lvm_pool
    type: disk
ephemeral: false
profiles:
- myfile
- default
stateful: false
description: ""
```
 - [X ] architecture: x86_64
 - [ X] Main daemon log (at /var/log/incus/incusd.log) (attached ubu2204-pw.info.txt)
[ubu2204-pw.info.txt](https://github.com/lxc/incus/files/15246075/ubu2204-pw.info.txt)

 - [X ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)
File incus_monitor.txt has been attached 
[incus_monitor.txt](https://github.com/lxc/incus/files/15247476/incus_monitor.txt)

 - [ X] Output of the client with --debug
  At the end of the log it shows this:
	```
	"expanded_devices": {
			"PwSocket1": {
				"bind": "container",
				"connect": "unix:/run/user/1111/pulse/native",
				"listen": "unix:/run/pipe-native",
				"mode": "0777",
				"type": "proxy"
			},
			"eth0": {
				"name": "eth0",
				"network": "incusbr0",
				"type": "nic"
			},
			"root": {
				"path": "/",
				"pool": "lvm_pool",
				"type": "disk"
			}
		},
```
